### PR TITLE
#47 use `$TMPDIR` as  when set

### PR DESCRIPTION
**Pull request by readefries**
Use $TMPDIR from environment when set

### CODE REVIEW

**Comment by wener-tiobe** [comment]
Thank you for your contribution. What is it that you want to achieve? Your proposed change is not in line wirh our intended behavior. So I'd like to understand what the intention/goal is.

**Comment by readefries** [comment]
Tics now ignores the system setting of what the proper TMPDIR location is. Which on POSIX is set in the environment variable TMPDIR*. As selinux blocks the use of executing files on `/tmp` of `/var/tmp` (due to it's global scope is a security issue), we need to be able to pass a TMPDIR which has to correct permissions to execute upon. We use this in almost all our workflows on custom VM runners so they can use a prepared `TMPDIR` location which is scoped for the current run.

```This variable shall represent a pathname of a directory made available for programs that need a place to create temporary files.```
See: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

**Comment by wener-tiobe** [comment]
This has been logged in our issue tracker: https://redmine.tiobe.com/issues/31395
The TICS option -tmpdir is not to be confised with the POSIX tmpdir. I cannot adopt the proposed change and will therefore close this pull request. Any changes to this topic are to be implemented in TICS itself, not the Github Action.

**Comment by readefries** [comment]
Thanks for the update, as long is the issue is solved it doesn't matter how

**Pull request closed without merging**
